[tool.poetry]
name = "VibrationCompensation"
version = "0.1.0"
description = ""
authors = ["Fred Sundvik"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7.2"
scipy = "1.3.0"
bokeh = "1.2.0"
colorcet = "1.0.1"

[tool.poetry.dev-dependencies]
sympy = "1.4"
antlr4-python3-runtime = "4.7.2"
jupyterlab = "0.35.6"
jupytext = "1.1.6"
pylint = "2.3.1"
pytest = "4.6.3"
pytest-pycharm = "0.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
